name: Build & Publish (devcontainer)

on:
  push:

env:
  DOTNET_FRAMEWORK: net8.0
  NEO_INSTALL_PATH: /opt/neo-cli

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository_owner }}/neo-cli
        imageTag: dev
        runCmd: |
          sudo mkdir -vp ${{ env.NEO_INSTALL_PATH }}
          sudo chgrp users ${{ env.NEO_INSTALL_PATH }}
          sudo chmod a+rwx ${{ env.NEO_INSTALL_PATH }}
          dotnet publish ./src/Neo.CLI \
            --framework ${{ env.DOTNET_FRAMEWORK }} \
            --configuration Release \
            --output ${{ env.NEO_INSTALL_PATH }} \
            --verbosity normal \
            --version-suffix dev
          screen -dmS neo ${{ env.NEO_INSTALL_PATH }}/neo-cli
