name: Test (neo-cli)

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      with:
        # Change this to point to your image name
        imageName: ghcr.io/${{ github.repository_owner }}/neo:latest
        # Change this to be your CI task/script
        runCmd: |
          # Add multiple commands to run if needed
          apt-get update && apt-get install -y libleveldb-dev
          dotnet test
