name: Generate Documentation
on:
  push:
    branches:
      - doc
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x  # Or your required .NET version

      - name: Install DocFx
        run: dotnet tool install --global docfx

      - name: Generate Documentation
        run: |
          export PATH="$PATH:/home/runner/.dotnet/tools"
          docfx docfx.json

      - name: Publish Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # or your DocFx output directory
