name: Publish (docker-image)

on:
  release:
    types: [published]

env:
  DIST_DIR: ./dist

jobs:
  neo-cli-build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Application Version (Environment Variable)
      run: |
        APP_VERSION=$(echo '${{ github.event.release.tag_name }}' | cut -d 'v' -f 2)
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

    - name: Checkout (GitHub)
      uses: actions/checkout@v4

    - name: Build (neo-cli)
      run: |
        dotnet publish ./src/Neo.CLI \
          --version-suffix linux-x64 \
          --framework net8.0 \
          --configuration Release \
          --runtime linux-x64 \
          --self-contained true \
          --output ${{ env.DIST_DIR }}/dist \
          --verbosity normal \
          -p:VersionPrefix=${{ env.APP_VERSION }} \
          -p:RuntimeIdentifier=linux-x64 \
          -p:SelfContained=true \
          -p:IncludeNativeLibrariesForSelfExtract=false \
          -p:PublishTrimmed=false \
          -p:PublishSingleFile=true \
          -p:PublishReadyToRun=true \
          -p:EnableCompressionInSingleFile=true \
          -p:DebugType=embedded \
          -p:ServerGarbageCollection=true

    - name: Build (LevelDbStore)
      run: |
        dotnet build ./src/Plugins/LevelDBStore \
          --version-suffix linux-x64 \
          --framework net8.0 \
          --configuration Release \
          --output ${{ env.DIST_DIR }}/dist/Plugins/LevelDBStore \
          --verbosity normal \
          -p:VersionPrefix=${{ env.APP_VERSION }}

    - name: Remove (junk)
      run: |
        rm -v ${{ env.DIST_DIR }}/dist/Plugins/LevelDBStore/Neo*
        rm -v ${{ env.DIST_DIR }}/dist/Plugins/LevelDBStore/*.pdb
        rm -v ${{ env.DIST_DIR }}/dist/Plugins/LevelDBStore/*.xml
        rm -v ${{ env.DIST_DIR }}/dist/*.xml

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        push: true
        file: .neo/docker/neo-cli/Dockerfile
        tags: |
          ghcr.io/${{ github.repository_owner }}/neo-cli:latest
          ghcr.io/${{ github.repository_owner }}/neo-cli:${{ env.APP_VERSION }}
