name: Release (neo-cli)

on:
  release:
    types: [published]

env:
  DOTNET_VERSION: 8.0.x
  CONFIGURATION: Release
  DIST_PATH: /tmp/dist
  OUTPUT_PATH: /tmp/out

jobs:
  build-leveldb:
    name: Build leveldb (windows-latest)
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
    - name: Lookup Cache Distribution
      id: cache-leveldb
      uses: actions/cache@v4
      with:
        path: ./leveldb/build/Release/*
        key: leveldb-windows-${{ matrix.arch }}
        enableCrossOsArchive: true
        lookup-only: true

    - if: ${{ steps.cache-leveldb.outputs.cache-hit != 'true' }}
      name: Checkout Repository Code (leveldb)
      uses: actions/checkout@v4
      with:
        repository: google/leveldb
        path: leveldb
        submodules: true
        fetch-depth: 0

    - if: ${{ steps.cache-leveldb.outputs.cache-hit != 'true' }}
      name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - if: ${{ steps.cache-leveldb.outputs.cache-hit != 'true' }}
      name: Setup LevelDb
      working-directory: ./leveldb
      run: mkdir -p ./build/Release

    - if: ${{ steps.cache-leveldb.outputs.cache-hit != 'true' }}
      name: Create Build Files (win-${{ matrix.arch }})
      working-directory: ./leveldb/build
      run: cmake -DBUILD_SHARED_LIBS=ON -A ${{ matrix.arch }} ..

    - if: ${{ steps.cache-leveldb.outputs.cache-hit != 'true' }}
      name: Build (MSBuild)
      working-directory: ./leveldb/build
      run: msbuild ./leveldb.sln /p:Configuration=Release

    - if: ${{ steps.cache-leveldb.outputs.cache-hit != 'true' }}
      name: Cache Distribution
      uses: actions/cache/save@v4
      with:
        path: ./leveldb/build/Release/*
        key: leveldb-windows-${{ matrix.arch }}
        enableCrossOsArchive: true

  build-neo-cli:
    needs: [build-leveldb]
    name: Build TarBalls (${{ matrix.runtime }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [linux-x64, linux-arm64, win-x64, win-arm64]

    steps:
    - name: Set Application Version (Environment Variable)
      run: |
        APP_VERSION=$(echo '${{ github.event.release.tag_name }}' | cut -d 'v' -f 2)
        echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

    - name: Checkout Repository Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: .NET Publish (neo-cli)
      run: |
        dotnet publish ./src/Neo.CLI \
        --version-suffix ${{ env.APP_VERSION }}
        --framework net8.0 \
        --configuration ${{ env.CONFIGURATION }} \
        --runtime ${{ matrix.runtime }} \
        --self-contained true \
        --output ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }} \
        --verbosity normal \
        -p:RuntimeIdentifier=${{ matrix.runtime }} \
        -p:SelfContained=true \
        -p:IncludeNativeLibrariesForSelfExtract=false \
        -p:PublishTrimmed=false \
        -p:PublishSingleFile=true \
        -p:PublishReadyToRun=true \
        -p:EnableCompressionInSingleFile=true \
        -p:DebugType=embedded \
        -p:ServerGarbageCollection=true

    - name: .NET Build (LevelDBStore)
      run: |
        dotnet build ./src/Plugins/LevelDBStore/LevelDBStore.csproj \
        --framework net8.0 \
        --configuration ${{ env.CONFIGURATION }} \
        --output ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}/Plugins/LevelDBStore \
        --verbosity normal

    - name: Remove Xml Comment Files
      working-directory: ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}
      run: rm -v *.xml

    - if: ${{ startsWith(matrix.runtime, 'win-x64') }}
      name: Get Distribution Caches (win-x64)
      uses: actions/cache@v4
      with:
        path: ./leveldb/build/Release/*
        key: leveldb-windows-x64
        enableCrossOsArchive: true
        fail-on-cache-miss: true

    - if: ${{ startsWith(matrix.runtime, 'win-arm64') }}
      name: Get Distribution Caches (win-arm64)
      uses: actions/cache@v4
      with:
        path: ./leveldb/build/Release/*
        key: leveldb-windows-arm64
        enableCrossOsArchive: true
        fail-on-cache-miss: true

    - if: ${{ startsWith(matrix.runtime, 'win') }}
      name: Copy Files (leveldb) (win)
      run: cp -v ./leveldb/build/Release/leveldb.dll ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}/libleveldb.dll

    - name: Create Distribution Directory
      run: mkdir -p ${{ env.DIST_PATH }}

    - name: Create Tarball File (linux)
      if: ${{ startsWith(matrix.runtime, 'linux') }}
      working-directory: ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}
      run: tar -czvf ${{ env.DIST_PATH }}/neo-cli-${{ matrix.runtime }}.v${{ env.APP_VERSION }}.tar.gz .

    - name: Create Zip File (win)
      if: ${{ startsWith(matrix.runtime, 'win') }}
      working-directory: ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}
      run: zip ${{ env.DIST_PATH }}/neo-cli-${{ matrix.runtime }}.v${{ env.APP_VERSION }}.zip -r *

    - name: Create Checksum Files
      working-directory: ${{ env.DIST_PATH }}
      env:
        FILENAME: neo-cli-${{ matrix.runtime }}.v${{ env.APP_VERSION }}
      run: |
          sha256sum ${{ env.FILENAME }}.tar.gz > ${{ env.FILENAME }}.sha256
          sha256sum ${{ env.FILENAME }}.zip > ${{ env.FILENAME }}.sha256

    - name: Output/Distribution Directory Contents
      run: |
        ls -la ${{ env.DIST_PATH }}
        ls -la ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}

    - name: Upload Tarball File (linux)
      if: ${{ startsWith(matrix.runtime, 'linux') }}
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.DIST_PATH }}/neo-cli-${{ matrix.runtime }}.v${{ env.APP_VERSION }}.tar.gz
          asset_name: neo-cli-${{ matrix.runtime }}.v${{ env.APP_VERSION }}.tar.gz
          asset_content_type: application/x-gtar

    - name: Upload Zip File (win)
      if: ${{ startsWith(matrix.runtime, 'win') }}
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.DIST_PATH }}/neo-cli-${{ matrix.runtime }}.v${{ env.APP_VERSION }}.zip
          asset_name: neo-cli-${{ matrix.runtime }}.v${{ env.APP_VERSION }}.zip
          asset_content_type: application/zip

    - name: Upload Checksum File (all)
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.DIST_PATH }}/neo-cli-${{ matrix.runtime }}.v${{ env.APP_VERSION }}.sha256
          asset_name: neo-cli-${{ matrix.runtime }}.v${{ env.APP_VERSION }}.sha256
          asset_content_type: text/plain

  # codesign-macos:
  #   name: Build TarBalls (${{ matrix.runtime }})
  #   runs-on: macos-latest
  #   strategy:
  #     matrix:
  #       runtime: [osx-x64, osx-arm64]

  #   steps:
  #   - name: Set Application Version (Environment Variable)
  #     run: |
  #       APP_VERSION=$(echo '${{ github.event.release.tag_name }}' | cut -d 'v' -f 2)
  #       echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

  #   - name: Checkout Repository Code
  #     uses: actions/checkout@v4
  #     with:
  #       fetch-depth: 0

  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       dotnet-version: ${{ env.DOTNET_VERSION }}

  #   - name: .NET Publish (neo-cli)
  #     working-directory: ./neo
  #     run: |
  #       dotnet publish ./src/Neo.CLI \
  #       --version-suffix ${{ env.APP_VERSION }}
  #       --framework net8.0 \
  #       --configuration ${{ env.CONFIGURATION }} \
  #       --runtime ${{ matrix.runtime }} \
  #       --self-contained true \
  #       --output ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }} \
  #       --verbosity normal \
  #       -p:RuntimeIdentifier=${{ matrix.runtime }} \
  #       -p:SelfContained=true \
  #       -p:IncludeNativeLibrariesForSelfExtract=false \
  #       -p:PublishTrimmed=false \
  #       -p:PublishSingleFile=true \
  #       -p:PublishReadyToRun=true \
  #       -p:EnableCompressionInSingleFile=true \
  #       -p:DebugType=embedded \
  #       -p:ServerGarbageCollection=true

  #   - name: .NET Build (LevelDBStore)
  #     working-directory: ./neo-modules
  #     run: |
  #       dotnet build ./src/Plugins/LevelDBStore/LevelDBStore.csproj \
  #       --framework net8.0 \
  #       --configuration ${{ env.CONFIGURATION }} \
  #       --output ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}/Plugins/LevelDBStore \
  #       --verbosity normal

  #   - name: Remove Xml Comment Files
  #     working-directory: ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}
  #     run: rm -v *.xml

  #   - name: CodeSign (neo-cli)
  #     working-directory: ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}
  #     run: codesign --force --deep -s - neo-cli

  #   - name: Create Distribution Directory
  #     run: mkdir -p ${{ env.DIST_PATH }}

  #   - name: Create Tarball File
  #     working-directory: ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}
  #     run: tar -cJf ${{ env.DIST_PATH }}/neo-cli-${{ matrix.runtime }}-${{ github.event.inputs.version }}.tar.xz .

  #   - name: Output/Distribution Directory Contents
  #     run: |
  #       ls -la ${{ env.DIST_PATH }}
  #       ls -la ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}

  #   - name: Cache Distribution
  #     uses: actions/cache/save@v3
  #     with:
  #       path: ${{ env.DIST_PATH }}/*
  #       key: ${{ matrix.runtime }}

  cleanup:
    needs: [build-neo-cli]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH -L 100 | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              if [ "$cacheKey" != "leveldb-windows-x64" ] && [ "$cacheKey" != "leveldb-windows-arm64" ]
              then
                gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
              fi
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref }}
