name: Validate neo-modules Compilation with Local neo

on:
  push:
    branches: [check]
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build neo-modules [default: latest master;]'
        required: false
        default: 'master'  # or 'main', depending on your default branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout neo
      uses: actions/checkout@v2
      with:
        path: ./neo

    - name: Checkout neo-modules
      uses: actions/checkout@v2
      with:
        repository: neo-project/neo-modules
        path: ./neo-modules
        ref: ${{ github.event.inputs.ref }}

    - name: Patch neo-modules Directory.Build.props to use local neo
      run: |
        props_path="./neo-modules/src/Directory.Build.props"
        sed -i '/<PackageReference Include="Neo"/d' $props_path
        sed -i '/<\/ItemGroup>/i \    <ProjectReference Include="../../../neo/src/Neo/Neo.csproj" />' $props_path

    - name: Install dependencies
      run: |
        sudo apt-get --assume-yes install libleveldb-dev libsnappy-dev libc6-dev

    - name: Test neo-modules
      run: |
        cd neo-modules/
        dotnet test
